# Generated by Django 3.1.13 on 2021-09-29 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocabulary',
            old_name='text',
            new_name='content',
        ),
    ]
