# Generated by Django 3.1.13 on 2021-09-29 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0003_auto_20210929_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='title',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
    ]
