# Generated by Django 3.1.13 on 2021-10-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0006_auto_20211004_0600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='searched_datetime',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='starred',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
